version: '3.8'

volumes:
  starclaw-data:
    name: starclaw-data
  starclaw-secrets:
    name: starclaw-secrets

services:
  starclaw:
    image: efairy/StarClaw:latest
    container_name: starclaw
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    # environment:
    #   - STARCLAW_AUTH_ENABLED=true
    #   - STARCLAW_AUTH_USERNAME=admin
    #   - STARCLAW_AUTH_PASSWORD=yourpassword
    volumes:
      - starclaw-data:/app/working
      - starclaw-secrets:/app/working.secret
